### ISSUE TITLE
IE 11 compatibility issue on trigger input.click()

### ISSUE THREAD

**Issue by tleperou** [tim-evans/ember-file-upload#103]
With IE 11, click on the button does not trigger the click on the input file.

If it's a known limitation of IE to simulate the trigger on the input file, then use ie-detect to downgrade the button on IE 11?

Other ideas?

**Comment by tleperou** [comment]
The solution is to avoid using a tagName `a` and bubbling e.preventDefault() somewhere.

e.g.
```
    {{#file-upload name='queueName' multiple=false onfileadd=(action (perform changeFile))}}
          <span class="button"><i class="fa fa-upload"></i> Upload me</span>
     {{/file-upload}}
```

**Comment by tleskin** [comment]
It might make sense if this was documented somewhere. I ran into this with our app in IE11 and thought it was an unknown bug in ember-file-upload since it also happens in the demo app.
