### ISSUE TITLE
Uncaught TypeError: Cannot read property 'registerWaiter' of undefined

### ISSUE THREAD

**Issue by artcommacode** [tim-evans/ember-file-upload#114]
It seems as if in production builds on Ember 3.0.0 `ember-file-upload` is expecting `Ember.Test` to exist when it doesn't and thus crashing the app. The issue occurs at https://github.com/tim-evans/ember-file-upload/blob/82598cf3e5828e78911742c048adbf83a59033df/addon/file.js#L112

Please let me know if you need any further information.

**Comment by artcommacode** [comment]
Looking at other issues it seems as if this should probably be wrapped in a `DEBUG`? More at https://github.com/emberjs/ember.js/issues/15670#issuecomment-329980787

**Comment by tim-evans** [comment]
Fixed in 2.2.6
