### ISSUE TITLE
Use onfileadd without file-upload

### ISSUE THREAD

**Issue by kmichek** [tim-evans/ember-file-upload#120]
Hi, I have a custom list of files to be uploaded, as well as custom buttons to maintain and upload the files, and have not figured how to use {{file-upload}} for that. I would still like to use the component. Is there a way how to invoke "onfileadd" or trigger the upload from my own list, please? Maybe I just need to learn how to create an instance of your file, just to be able to trigger file.upload ? 
Thank you for your suggestions.

**Comment by tim-evans** [comment]
Hi @kmichek, it sounds like you'd like to use the `upload` method on a file. (Sorry about the lacking documentation)

You can import the file by importing the File object from `ember-file-upload/file`. I think you'll be able to create a file object by creating it using `File.fromBlob(file)`. After doing that, you can follow the docs and `upload` that file 😄

**Comment by kmichek** [comment]
Hi, yes, that works perfect. Thank you very much!
