### ISSUE TITLE
Dropzone doesn't work

### ISSUE THREAD

**Issue by Padchi** [tim-evans/ember-file-upload#13]
With the code from [test]( https://github.com/tim-evans/ember-file-upload/blob/master/tests/dummy/app/templates/index.hbs) (tried with the code from the readme too).
 Nothing happens when i try to drag a image from my desktop to the "dropzone". With the code linked above the text should be `Cat eating file Drag and drop cat photos!` but it's still `Normal Cat Drag and drop cat photos!`. If i drop the file Safari and Chrome redirects to the the URL `(file:///xxx/Desktop/14123583_10153908003751849_1066675195_o.jpg)`

I have tested the code both in a component and a controller template, same thing.

Using Ember 2.8.1 and tested with Safari 10.0, Chrome 53.0.2785.143.

**Comment by tim-evans** [comment]
The test suite for this doesn't pass yet. :P

**Comment by Padchi** [comment]
Well it's the same thing with the code from the readme ;) drag and drop dosn't work for me.

Skickat från min iPhone

**Comment by tim-evans** [comment]
Ok, I'll take a peek when I have some time

**Comment by tim-evans** [comment]
It should work now :)
