### ISSUE TITLE
Camera capture attribute

### ISSUE THREAD

**Issue by yashprit** [tim-evans/ember-file-upload#130]
Hi, we are using this plugin for mobile app and don't want to use Cordova to capture image. will it possible to add attribute to capture camera? It looks like to just add an attribute called capture pass same to template default will be nothing. 

Please let me know what do you think about it? if yes I'll send you pull request for same

Thanks

**Comment by tim-evans** [comment]
Yeah, feel free to PR

**Comment by lougreenwood** [comment]
@yashprit did you get anywhere with this?

**Comment by yashprit** [comment]
@lougreenwood sadly nothing started, got busy with other work, and its still bug in our system :( soon i'll resume work on it
