### ISSUE TITLE
Safari drag and drop

### ISSUE THREAD

**Issue by dbollinger** [tim-evans/ember-file-upload#136]
I'm on v2.4.2 of the add-on and having problems with Safari (v11.0.1).  Should this be working out of the box, or are there things that need to be explicitly configured for Safari compatibility?  I looked at #42  and #79 and it doesn't seem like anything should have to be configured. 

Specifically, I'm getting the error in `drag-listener.js`, in the function `getDataTransferItemDetails(evt)` with the error `undefined is not an object (evaluating 'evt.dataTransfer.items.length')`

It looks like the demo page is also failing in Safari here: http://tim-evans.github.io/ember-file-upload/latest/

**Comment by schleifer-john** [comment]
I tested both my local application and the demo page (http://tim-evans.github.io/ember-file-upload/latest/) in Safari with ember-file-upload@2.4.4.  Drag & Drop is working again.

@tim-evans I think this issue can be closed.

**Comment by tim-evans** [comment]
Thanks!
