### ISSUE TITLE
Replace jQuery's findWithAssert in test helper upload

### ISSUE THREAD

**Issue by imalexsq** [tim-evans/ember-file-upload#138]
helpers/upload.js is using jQuery's findWithAssert which was removed from Ember 3.0. Ember test gives 'findWithAssert is not defined' error.

**Comment by imalexsq** [comment]
I've been trying to solve this issue and here are my findings so far:

1. `let input = findWithAssert(selector)[0];` can be replaced with Ember's find method like so `fileInput = find('.file-upload input');`

2. `file.name = filename;` does not work as file.name is read-only string

3. After a file is added, I cannot seem to access it through FileList object in the console. I'm not sure where this file is stored.

**Comment by tim-evans** [comment]
See https://github.com/tim-evans/ember-file-upload/pull/89

If you could help kick that PR over the finish line, it would be very appreciated ♥️

**Comment by imalexsq** [comment]
@tim-evans I'd love to contribute, but I'll need some help. Can you chat over EmberJS Slack channel?

**Comment by tim-evans** [comment]
That i can! I’m @tce over there. I’ll probably respond tomorrow during NYC work hours
