### ISSUE TITLE
Typo in flushFilesWhenSettled and getting 'Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by Padchi** [tim-evans/ember-file-upload#14]
Think `file.status` should be `file.state` [here](https://github.com/tim-evans/ember-file-upload/blob/master/addon/services/file-queue.js#L78)?

Also, `set(this, 'files', Ember.A())` gives me `RangeError: Maximum call stack size exceeded`

**Comment by Padchi** [comment]
Still getting `Maximum call stack size exceeded` on line [#83](https://github.com/tim-evans/ember-file-upload/blob/master/addon/services/file-queue.js#L83)

**Comment by tim-evans** [comment]
😞
