### ISSUE TITLE
Internet Explorer 11 - Drag / Drop functionality broken

### ISSUE THREAD

**Issue by schleifer-john** [tim-evans/ember-file-upload#141]
I'm currently using version Ember File Upload 2.4.2 and it appears that the Drag / Drop functionality in IE 11 does not work.

I get the following error when attempting to use the feature:

> SCRIPT5007: Unable to get property 'length' of undefined or null reference

This is the offending line of code: https://github.com/tim-evans/ember-file-upload/blob/latest/addon/system/drag-listener.js#L107

I compared the DataTransfer object in both IE and Chrome and it looks like the `items` variable of type `DataTransferItemList` is missing in IE.  Upon further investigation, it looks like this object is not supported in IE.
See: https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList

**Comment by schleifer-john** [comment]
This issue may also be related to https://github.com/tim-evans/ember-file-upload/issues/136 as DataTransferItemList is not supported in Safari either.

**Comment by schleifer-john** [comment]
I rolled back to ember-file-upload@2.0.0 and the Drag / Drop feature still didn't work for me with IE.  So it seems there is something in the core logic outside of `DataTransferItemList` that needs to be fixed.  I will do some more troubleshooting next week and see if I can find some more information.

**Comment by schleifer-john** [comment]
I did some more debugging.  For me, the `findListener` method is not able to find the drop listener.

https://github.com/tim-evans/ember-file-upload/blob/latest/addon/system/drag-listener.js#L88

I am using a setup similar to the example in the README: 
```
{{#file-dropzone name="photos" as |dropzone queue|}}
  {{#if dropzone.active}}
    {{#if dropzone.valid}}
      Drop to upload
    {{else}}
      Invalid
    {{/if}}
  {{else if queue.files.length}}
    Uploading {{queue.files.length}} files. ({{queue.progress}}%)
  {{else}}
    <h4>Upload Images</h4>
    <p>
      {{#if dropzone.supported}}
        Drag and drop images onto this area to upload them or
      {{/if}}
      {{#file-upload name="photos"
                     accept="image/*"
                     multiple=true
                     onfileadd=(route-action "uploadImage")}}
        <a id="upload-image" tabindex=0>Add an Image.</a>
      {{/file-upload}}
    </p>
  {{/if}}
{{/file-dropzone}}
```

Basically, in IE the `element` object is one div tag (id=ember2) and `evt.target` is another (id=ember1):

```
<div id="ember1">
   <div>
      <div id="ember2">
      </div>
   </div>
</div>
```
For some reason in IE, `element` is the child and `evt.target` is the parent, so `element.contains(evt.target)`  will always evaluate to false as the child cannot contain the parent.  I added the inverse condition and it fixed the issue for me:
```
  findListener(evt) {
    return this._listeners.find(function ({ selector }) {
      let element = document.querySelector(selector);
      return element === evt.target || element.contains(evt.target) || evt.target.contains(element);
    });
  }
```

In Chrome `element === evt.target` evaluates to true.  I'm wondering if the bug could be that the order is incorrect for `element.contains(evt.target)`?  Is there ever a scenario where that condition evaluates to true?  Does it hurt to have all 3 conditions?

**Comment by schleifer-john** [comment]
I retested this after 2.4.4 was released and the issue is resolved.  Closing this issue.

**Comment by Caltor** [comment]
This isn't working for me with version 2.7.1 of ember-file-upload. Here is a MCVE. This works fine in Chrome and Firefox but in IE 11 when you drag files over the dropzone the message changes to "Drop to upload" and just sticks there but nothing actually happens. I have ensured that IE 11 is a target in config/targets.js and that polyfill is enabled in the ember-cli-build.js as follows.

```
'ember-cli-babel': {
    includePolyfill: true
},

```
**template.hbs**
```
<div class="alert alert-info">
    {{#file-dropzone name="photos" as |dropzone queue|}}
        {{#if dropzone.active}}
            {{#if dropzone.valid}}
                Drop to upload
            {{else}}
                Invalid
            {{/if}}
        {{else if queue.files.length}}
            Uploading {{queue.files.length}} files. ({{queue.progress}}%)
        {{else}}
            <h4>Upload Images</h4>
            <p>
                {{#if dropzone.supported}}
                    Drag and drop images onto this area to upload them or
                {{/if}}
                {{#file-upload name="photos"
                     multiple=true
                     onfileadd=(action "uploadImage")}}
                    <span id="upload-image" tabindex="0" class="span-link">Add an Image.</span>
                {{/file-upload}}
            </p>
        {{/if}}
    {{/file-dropzone}}
</div>
```

**controller.js**
```
import Controller from '@ember/controller';

export default Controller.extend({
    actions: {
        uploadImage(file) {
            console.log("uploadImage fired!");
            console.log("file: ", file);
            file.upload("http://localhost:4201/api/document-store").then(x => {
                console.log("x: ", x);
            }, y => {
                console.error("y: ", y);
            });
        }
    }
});


```
