### ISSUE TITLE
upload test-helper does not trigger upload

### ISSUE THREAD

**Issue by ondrejsevcik** [tim-evans/ember-file-upload#144]
Hi, I can't figure out what am I doing wrong, but the upload helper is not working for me. I have a following acceptance test

```js
module('Acceptance | upload', function(hooks) {
  setupApplicationTest(hooks);

  test('upload works', async function(assert) {
    await visit('/');

    let file = File.fromDataURL('data:image/gif;base64,R0lGODdhCgAKAIAAAAEBAf///ywAAAAACgAKAAACEoyPBhp7vlySqVVFL8oWg89VBQA7');
    await upload('#upload-photo', file, 'smile.gif');

    let photo = server.db.photos[0];
    assert.equal(photo.filename, 'smile.gif');
  });
});
```

which is basically what's in the README. I can see that upload helper is being called with my input selector, but when I put a `debugger;` into the JS code, I can also see that my `onaddfile` handler is not called and thus nothing is uploaded to the server.

What am I doing wrong?

EDIT:

After a bit of investigation, I've found this line https://github.com/tim-evans/ember-file-upload/blob/latest/addon/queue.js#L68. The problem here is that in the example we use File (ember model) but this code requires File (native browser object).

I also had to comment out this line https://github.com/tim-evans/ember-file-upload/blob/latest/test-support/helpers/upload.js#L6 because File.name is readonly. 

Now it's working. 

I can do a PR to fix this issue, if you're interested.

**Comment by tim-evans** [comment]
A PR would be great! There's another person that's working on this issue, I think.

**Comment by ondrejsevcik** [comment]
oh, I missed that. I think it's this one #89. It would be great to finish it :)

**Comment by tim-evans** [comment]
Yes, if could get that PR (or a variant of that) over the finish line, I'd very much appreciate it! ❤️

**Comment by tpetrone** [comment]
Hi @everybody!
Thanks for the effort, any updates on this?

**Comment by ondrejsevcik** [comment]
See mentioned PR for more info
