### ISSUE TITLE
Successful upload returns 303 / Redirect issues

### ISSUE THREAD

**Issue by lougreenwood** [tim-evans/ember-file-upload#155]
Hello,

The API which I'm using to upload the file returns a 303 status code with the location of the file in `response.headers.Location`

However, it seems that the presence of the 303 causes the request redirect to be followed, in our case, this results in a CORS error because the uploaded file resource isn't intended to be accessed by JS.

So it seems that our problem can be resolved in a number of ways, but I wanted to first get you input on whether the plugin supports a 303 response at all.

Our potential solutions:
- Add CORS rule to uploaded file host so that 303 doesn't trigger CORS/JS error
- Try to update API to return 2XX status code
- Some other upstream fix to the add-on which stops the request response redirect being followed

**Comment by tim-evans** [comment]
Adding a CORS option to uploads sounds good; I think this is possible currently? I haven't really dug into that in a while.

**Comment by lougreenwood** [comment]
I suppose that if the 303 is successfully followed then the browser will download the whole attached file and this may affect performance of upload (time to upload + time to download after following 303) as well as overall data usage of application?

(To be clear, the 303 response/redirect is an artefact of the API and not used in the application - only the `response.headers.Location` is of concern to the app)

I suppose that the proper fix would be would be to some options that allows the add-on to resolve on some other - non 2XX - user-defined status codes and also some way to disable following any redirects?

**Comment by tim-evans** [comment]
I'm not sure what the right solution is for this, I'd encourage you to fork and try to figure out a solution to this, since I don't have enough context or knowledge to solve this.

**Comment by lougreenwood** [comment]
Thanks for your help - we moved over to using `201 created` since this is still semantically correct and also allows us to return a 2XX status code, as `ember-file-upload` expects 👍
