### ISSUE TITLE
Multiple file uploads on same page

### ISSUE THREAD

**Issue by aysha-rafa** [tim-evans/ember-file-upload#173]
I have multiple file uploads in same page(let's say each uploader for each element) and when I click 'browse' on third  element's uploader, it gets third element's model first and then click event is again triggered and gets the first element's model(it also has uploader) and the uploading takes place in wrong element in the end. Why is this happening? Multiple file uploaders is not supported or is there any other logic happening behind?

PS: One uploader added in the component for all elements, but has different names(model's ID is givan as name.)

Thanks.

**Comment by jayvarner** [comment]
@aysha-rafa I had this same issue. It took me a while to realize I was not passing unique values for the `for` option to the `file-upload` component. Obviously, I'm just guessing here. Example (using `concat` from [Ember Composable Helpers](https://github.com/DockYard/ember-composable-helpers)

```handlebars
{{#each model as |item|
  {{#file-upload name=(concat 'upload-' item.id)
                 for=(concat 'upload-' item.id)
                 accept="image/*"
                 multiple=true
                 onfileadd=(action "uploadImage")}}
     <a id=(concat 'upload-' item.id) tabindex=0>Add an Image.</a>
  {{/file-upload}}
{{/each}}
```
I hope that helps.

**Comment by aysha-rafa** [comment]
@jayvarner Thank you for the reply. I was passing a unique ID, but my problem was [this ](https://github.com/tim-evans/ember-file-upload/issues/177) which is solved now.
