### ISSUE TITLE
Dropzone triggering events out of scope->which should not

### ISSUE THREAD

**Issue by aysha-rafa** [tim-evans/ember-file-upload#177]
Drag something outside dropzone area also triggers the "ondragenter" event. How to stop this? I want dropzone to restrict just to its given area. It is same here also [http://tim-evans.github.io/ember-file-upload/latest/](url)

**Comment by tim-evans** [comment]
Well, _that's_ broken. Thanks for the report; if you could provide a fix, that would be fantastic!

**Comment by aysha-rafa** [comment]
Sorry, I am totally new to Ember. Can you provide a fix for this please?
Thanks.

**Comment by tim-evans** [comment]
I will try to do so, I've been a tad busy, so it may be a bit. Pinging someone on the Ember discord may be good to start digging in! ❤️

**Comment by aysha-rafa** [comment]
I have updated it. Can you please review it! :)

**Comment by tim-evans** [comment]
Certainly! That's great to see a PR ❤️
