### ISSUE TITLE
`rect` is not a supported tagName inside `file-upload`

### ISSUE THREAD

**Issue by brandynbennett** [tim-evans/ember-file-upload#181]
Other svg elements are included such as `svg`, `circle`, `g`, `path`, etc. But not `rect`

**Comment by tim-evans** [comment]
OoOoO. A PR for this would be very welcome!

**Comment by jakemauer** [comment]
Just opened a PR for it here: https://github.com/tim-evans/ember-file-upload/pull/182

**Comment by tim-evans** [comment]
It’s released! I don’t have much time now to do release notes, but you’ll be thanked ❤️
