### ISSUE TITLE
ondragleave event does not work

### ISSUE THREAD

**Issue by angelomachado** [tim-evans/ember-file-upload#19]
Hi. First of all thank you for your work on this addon.
I have followed the readme instructions with the following template:
```handlebars
{{#with (file-queue for="files"
    accept=accept
    multiple=multiple
    onfileadd=(action "onfileadd"))
    as |queue|}}
  {{#with (file-dropzone
           for="files"
           queue=(file-queue for="files")
           ondragenter=(action "ondragenter")
           ondragleave=(action "ondragleave")
           ondrop=(action "ondrop"))
           as |dropzone|}}
    <div id="files" class="file-uploader">
```
ondragenter and ondrop events are working as expected but ondragleave isn't. It seems that [this](https://github.com/tim-evans/ember-file-upload/blob/master/addon/system/dropzone.js#L84) line is preventing the event from being fired. Any guidance on this?

**Comment by tim-evans** [comment]
Oh, this is still being tinkered with. What do you want to use `ondragleave` for?

The intention was for this to be used for validating and setting cursor properties.

**Comment by tim-evans** [comment]
Oh, and I may pull the rug out at any time- this is a *beta* addon.

**Comment by angelomachado** [comment]
> The intention was for this to be used for validating and setting cursor properties.

I have a similar intention.

> Oh, and I may pull the rug out at any time- this is a beta addon.

No problem. I am wrapping this addon into a component.

**Comment by tim-evans** [comment]
Super :)

**Comment by tim-evans** [comment]
Also, I welcome PRs to fix this :P

**Comment by tim-evans** [comment]
@angelomachado the most recent release may fix your issues.

**Comment by angelomachado** [comment]
That's nice to hear! Closing the issue.
