### ISSUE TITLE
 Could not find module 

### ISSUE THREAD

**Issue by wayne-o** [tim-evans/ember-file-upload#20]
get the following after installing the component and pasting the recipe into a new template:

`Could not find module `ember-file-upload/components/file-dropzone/component` imported from `signum-ui/components/file-dropzone``

DEBUG: -------------------------------
ember.debug.js:5732DEBUG: Ember             : 2.10.0
ember.debug.js:5732DEBUG: Ember Data        : 2.10.0
ember.debug.js:5732DEBUG: jQuery            : 3.1.1
ember.debug.js:5732DEBUG: Ember Simple Auth : 1.1.0
ember.debug.js:5732DEBUG: -------------------------------

**Comment by tim-evans** [comment]
Is `ember-file-upload` in your `require.entries`?

**Comment by wayne-o** [comment]
How do I modify require.entries?

**Comment by tim-evans** [comment]
You don't. It's there to let you know that it's been required as a module properly.

**Comment by chrisdpeters** [comment]
@tim-evans I did the same as @wayne-o and am getting the same error.

Here is what `require.entries` lists for me for `ember-file-upload`:

```
ember-file-upload/components/file-upload/component
ember-file-upload/components/file-upload/template
ember-file-upload/computed/sum-by
ember-file-upload/file
ember-file-upload/helpers/file-dropzone
ember-file-upload/helpers/file-queue
ember-file-upload/queue
ember-file-upload/services/file-queue
ember-file-upload/system/data-transfer
ember-file-upload/system/dropzone
ember-file-upload/system/file-reader
ember-file-upload/system/http-request
ember-file-upload/system/trim
ember-file-upload/system/uuid
```

Looks like the list is indeed missing `ember-file-upload/components/file-dropzone/component`.

I am using Ember 2.8.3 myself.

**Comment by chrisdpeters** [comment]
Looks like this broke in [2.0.0-beta.9](https://github.com/tim-evans/ember-file-upload/commits/2.0.0-beta.9/addon/components/file-dropzone/component.js) while you were moving `file-dropzone` from a component to a helper.

@tim-evans, Is there anything that I can do to help with this? I'm not sure what your motivation is for this change, but I may be able to help with some further explanation.

**Comment by tim-evans** [comment]
My thought was that it was easier managing a dropzone this way. You could use ember-elsewhere or ember-wormhole to move the dropzone where you wanted to and render it in the template you'd like. It also cleaned up the weirdness around using the `file-queue` helper, which felt more intimate.

**Comment by tim-evans** [comment]
Looking into this. This seems very strange. I don't know what's going on..

**Comment by tim-evans** [comment]
Seems like it was a messed up npm publish perhaps. It's fixed anyways.

**Comment by chrisdpeters** [comment]
@tim-evans Appears to be working much better now. Thank you for your help. Now on to getting it working with my API, etc...

**Comment by tim-evans** [comment]
👍
