### ISSUE TITLE
Drag-and-drop isn't working with IE11 (and let's face it, probably other versions of IE)

### ISSUE THREAD

**Issue by chrisdpeters** [tim-evans/ember-file-upload#21]
When dropping a file from Windows Explorer into IE11, I get this error in the console: `SCRIPT87: Invalid argument.`.

It then proceeds to highlight [this line](https://github.com/tim-evans/ember-file-upload/blob/85b48afd2694f5e95fd6d8590b16910d09ef5e24/addon/components/file-dropzone/component.js#L121) from `file-dropzone/component.js`:

```javascript
let url = evt.dataTransfer.getData('text/uri-list');
```

I've scoured Google looking for a way to help fix this. I tried changing `text/uri-list` to `URL` [per MSDN](https://msdn.microsoft.com/en-us/library/ms536436(v=vs.85).aspx) with no success. (`console.log(url)` ends up evaluating to `undefined`.)

I'm not sure if you're interested in supporting IE or if this even works in Edge, but I thought that I would log what I've run into here if anyone was interested in fixing it.

**Comment by tim-evans** [comment]
Ahh, we can `try` / `catch` this to make sure it doesn't fail.

**Comment by tim-evans** [comment]
(PS. I ❤️ PRs)

**Comment by chrisdpeters** [comment]
@tim-evans Honestly, I was poking around for an hour and a half trying to find a way to submit a PR-with-fix instead of just a lazy you-fix-it issue. I'd be glad to help, but I'd need a pointer or two on what to try. I'm out of ideas.

**Comment by tim-evans** [comment]
Haha, ok! I think a good step would be to do a trial check to see if you can drag and drop using files in a browser. This also should probably be a feature that can be disabled if not supported by the browser.

So, I think maybe going to `file-dropzone`:

```js
try {
  evt.dataTransfer.getData('text/uri-list');
  this.set('supportsUrls', true);
} catch () {
  this.set('supportsUrls', false);
}
```
