### ISSUE TITLE
_addFiles not a function

### ISSUE THREAD

**Issue by patrickng** [tim-evans/ember-file-upload#24]
With Ember 2.11.0, I keep getting this error in the console after choosing a file to upload. I tried downgrading to 2.8.3 but the latest beta still gives me that same problem.

```
Uncaught TypeError: _get(...)._addFiles is not a function
    at Class.change (component.js:58)
    at Backburner.run (ember.debug.js:294)
    at Backburner.join (ember.debug.js:318)
    at Function.run.join (ember.debug.js:23765)
    at ember.debug.js:11710
    at Object.flaggedInstrument (ember.debug.js:20159)
    at HTMLInputElement.closureAction (ember.debug.js:11709)
```
which seems to be pointing to this bit of code:
```
    actions: {
      change: function change(files) {
        _get(this, 'queue')._addFiles(files);
      }
    }
```

**Comment by patrickng** [comment]
A little bit more information: The file upload feature last works for me with Ember 2.8.3 and ember-file-upload 2.0.0-beta.21

**Comment by patrickng** [comment]
After re-reading the README and digging through the source code, I realize this is not an issue. There was a change to how the component should be used, moving the attributes onto the file-upload block instead of using a "with" block fixes my problem. Sorry about this!

**Comment by tim-evans** [comment]
No problem! Maybe I can provide better errors to prevent this from happening 👍

**Comment by samselikoff** [comment]
@patrickng running into the same thing - would love a summary of what changes you made!

**Comment by samselikoff** [comment]
I think I got it — just moved accept, multiple and onfileadd from the `file-queue` helper to the `file-upload` component:

```
{{#file-upload name="image"
  accept="image/*"
  multiple=false
  onfileadd=(perform upload)}}
```

**Comment by tim-evans** [comment]
^ @samselikoff yup, that's the approach.

What documentation made this unclear? I'd like to fix that.

**Comment by samselikoff** [comment]
@tim-evans I was upgrading code I hadn't written that used `{{#with (file-queue...`, saw the new example put those attrs on `{{#file-upload...` but as we weren't using drag-and-drop I didn't know if my code was just a simpler version. Basically couldn't see a meaningful error that `file-queue` changed.

I think versioning would help here, if `file-upload`'s API changed just bump the major and make a comment in changelog. At least that's what I was expecting

**Comment by samselikoff** [comment]
— says the LAST person who should be lecturing on semver (mirage out for 2 years and not at 1.0 yet... 🙄)

**Comment by tim-evans** [comment]
@samselikoff haha, yes. That would help a lot.

I didn't realize how many people were using this. Guess it's time now to make that docs portal a thing. I've also been tweaking the API ad-hoc, but I think it's in a stable place now and may make it a 2.0.

For history, this was a rewrite of ember-plupload, so that's why it's pre 2.0. (Also because I want to make my test coverage much higher for this)

**Comment by tim-evans** [comment]
Thanks for the feedback! It helps sooo much to have that so I can make this better.

**Comment by patrickng** [comment]
Late to the thread! but yes, I was also in the process of upgrading and didn't notice the new template requirements.

**Comment by tim-evans** [comment]
Sorry about that y'all! 😅

**Comment by allthesignals** [comment]
This error can come up when you are using the wrong syntax for angle bracket invocation:

```
     Wrong!
      <FileUpload
        name='files'
        accept='image/*'
        onfileadd={{action 'uploadImage'}}
      >
        {{fa-icon 'upload'}} Upload Files
      </FileUpload>
```

```
     Right!
      <FileUpload
        @name='files'
        @accept='image/*'
        @onfileadd={{action 'uploadImage'}}
      >
        {{fa-icon 'upload'}} Upload Files
      </FileUpload>
```

Always helps to use the right syntax :)
