### ISSUE TITLE
Multiple uploads of the same file

### ISSUE THREAD

**Issue by lodrantl** [tim-evans/ember-file-upload#41]
Using the file-upload component, you can not upload the same file multiple times in a row, because the form is not cleared after file upload.
I know it sounds weird, but my latest application needs this use case. I have solved the problem by reopening the component and resetting the form like this.

```javascript
FileUpload.reopen({
  actions: {
    change(files) {
      this._super(files);
      this.$().children("input").val(null);
    }
  }
});
```
Do you think this could become a configurable attribute to the component or do you think it would cause some problems along the way?

**Comment by tim-evans** [comment]
What you did should be ok to do- we already have a reference to the file then 👍 

Could you make a PR for this? With tests would be ✨ amaaaazing:sparkles:

**Comment by lodrantl** [comment]
Will do later in the afternoon or tomorrow.

**Comment by mickeysanchez** [comment]
Is this fixed?

**Comment by tim-evans** [comment]
I don't think so.

**Comment by matthewdias** [comment]
this issue can be closed now, yeah?

**Comment by lodrantl** [comment]
I totally forgot about this... Thanks @mickeysanchez for the PR I promised. I'm closing this.

**Comment by tim-evans** [comment]
Thanks @matthewdias 👍
