### ISSUE TITLE
File-Dropzone + Safari 10.0.3

### ISSUE THREAD

**Issue by luis-carlos-campos** [tim-evans/ember-file-upload#42]
Hi there,

I Implement the simple example of your README and it worked like charm in Chrome, but when I tried it on Safari I noticed it was not working. I debugged your code and then I figured out that it was not working because Safari considers the source as web while Chrome considers as os...
So in order to make it work I had to use the allowUploadsFromWebsites.

I was wondering If there is something you can do or if it's Safari's problem.
Anyway maybe you guys can add a note about that limitation.

I did not tried it on a newer version of Safari, sorry had no time for that.

Thanks in advance,

Luis

**Comment by tim-evans** [comment]
Thanks @luis-carlos-campos ! This definitely sounds like a bug with this addon with Safari. I will try to add a test for this :)

**Comment by ryanjavens** [comment]
@luis-carlos-campos what error are you getting in Safari in your console? Is it a '_get(...) is null' error? I'm noticing that I get an error in Firefox when mousing over a dropzone utilizing the code that is in the example, but it doesn't occur in Chrome. The uploader still functions properly in Firefox as far as I can tell, the example is just locked into the dropzone.active state.

**Comment by donaldwasserman** [comment]
I'm experiencing a similar issue with safari 10.1.2 (on desktop)

When dragging a file on the dropzone, nothing seems to happen. 

When the element is inserted `dropzone.supported` is true, but  the dropzone itself doesn't emit any events. (File uploading by clicking seems to work fine though)

**Comment by tim-evans** [comment]
Oh noes!

**Comment by donaldwasserman** [comment]
if this is an issue that you know sort of where the right direction is to look, i can probably take a stab  at fixing it this week.

**Comment by tim-evans** [comment]
This probably has something to do with this function https://github.com/tim-evans/ember-file-upload/blob/master/addon/components/file-dropzone/component.js#L167-L239

**Comment by tim-evans** [comment]
Or newly added code dealing with https://github.com/tim-evans/ember-file-upload/commit/4f2304a93751db350d4121ae760e3d8e8113cbb0

**Comment by donaldwasserman** [comment]
ok. I just created a fork. hopefully will look into it in the next few days (when i resolve a few other issues based on bugs in my code)

**Comment by tim-evans** [comment]
thanks @donaldwasserman ❤️

**Comment by okachynskyy** [comment]
@tim-evans, any updates?
Dropzone still not working on Safari (10.1.1)  without `allowUploadsFromWebsites=true` config :(

**Comment by donaldwasserman** [comment]
Sorry - I was going to look into this, then got side tracked by a few other problems I created with the project I was using this for. I'll actually look into it on Monday, unless someone has an immediate solution.

**Comment by donaldwasserman** [comment]
Alright - I think I found the problem Will make a PR shortly.

**Comment by donaldwasserman** [comment]
One workaround is to set ‘allowUploadsFromWebsites’ to true
