### ISSUE TITLE
Mirage config `enabled` merging with host app

### ISSUE THREAD

**Issue by samselikoff** [tim-evans/ember-file-upload#44]
Upgrading to a recent version of the addon - very cool Mirage integration!!

But I think https://github.com/tim-evans/ember-file-upload/commit/8c68134430432e766fcc3523fd0e9d0865f9379e merges in with the host app. I am getting `enabled: true` in my host app's config (which is shipping Mirage to production for me). Consumers can explicitly disable Mirage in production environments, but we should try to preserve Mirage's defaults for end users.

Why did you need to enable Mirage in prod in the first place - for your dummy app at https://tim-evans.github.io/ember-file-upload/? In that case we should just enable Mirage in the app's config here https://github.com/tim-evans/ember-file-upload/blob/master/tests/dummy/config/environment.js

**Comment by tim-evans** [comment]
Oops, that was a mistake on my part! 😅

**Comment by tim-evans** [comment]
I'll definitely fix this to use the default mirage configuration- thanks for using this, by the way! :D

**Comment by tim-evans** [comment]
Fixed by https://github.com/tim-evans/ember-file-upload/releases/tag/2.0.0-beta.43

**Comment by samselikoff** [comment]
Nice, thanks!
