### ISSUE TITLE
file.upload() returning undefined

### ISSUE THREAD

**Issue by donaldwasserman** [tim-evans/ember-file-upload#51]
HI There - 

I'm pretty new to this library and ran into a problem that I can't wrap my brain around. I've used this library basically copy and paste from the example to upload files to s3. 

But when I try hitting my own server, `file.upload()` returns immediately as undefined, **but the http request does happen and hits the server successfully!**

I tried stepping through the code in the debugger, but can't quite make sense of why it's doing what it's doing. Any help would be appreciated.

**Comment by tim-evans** [comment]
This was a bug in 2.0.0, could you upgrade?

**Comment by donaldwasserman** [comment]
Oh thanks - learned an important lesson about the importance of checking the release notes...

Appreciate it. 

This addon is great by the way.

**Comment by tim-evans** [comment]
Thanks @donaldwasserman
