### ISSUE TITLE
How to include credentials

### ISSUE THREAD

**Issue by blainelang** [tim-evans/ember-file-upload#53]
Thanks Tim for your great contribution!

In my initial testing app, it's using the ember-simple-auth addon and basic auth. I haven't been able to figure out how to send the user credentials when calling the file.upload method.

I believe that I need to set the xhrFields ajax property to {withCredentials: true}.

Tried setting it via the headers as well as data property but no luck. 

This was my last attempt:
let response = file.uploadBinary(config.APP.API_HOST + '/file/upload/', {
    method: 'POST',
    headers: {'Content-Type': 'application/octet-stream', 'X-CSRF-TOKEN': csrf_token},
    data:  {'xhrFields': {withCredentials: true}},
});

**Comment by tim-evans** [comment]
You can pass `withCredentials: true` as a top-level option:

```
let response = file.uploadBinary(config.APP.API_HOST + '/file/upload/', {
  method: 'POST',
  withCredentials: true,
  headers: {'Content-Type': 'application/octet-stream', 'X-CSRF-TOKEN': csrf_token}
});
```

**Comment by tim-evans** [comment]
Also, `contentType` is not required here; it is set to `application/octet-stream` by default.

**Comment by blainelang** [comment]
Thanks Tim for your quick response. I had seen the the pull request #28 but was not sure how to apply it as there was no example (that I could see). 

Thanks again for your work!
