### ISSUE TITLE
{{simple-upload}} component without dropzone that provides fileQueue / progress

### ISSUE THREAD

**Issue by raido** [tim-evans/ember-file-upload#56]
Hi,

Currently I have done my own component that creates a queue manually, essentially using private APIs I guess? My use case is that I need only simple file upload button without dropzone but currently only the dropzone provides queue property.

**Comment by tim-evans** [comment]
@raido it may be poor documentation, but you can do this quite easily:

```hbs
{{#file-upload name="avatar" accept="image/*" onfileadd=(action 'upload')}}
  Upload
{{/file-upload}}
```

**Comment by raido** [comment]
Yes, but this component does not yield queue object where I could get progress property.

**Comment by tim-evans** [comment]
Ok, that's a helper that you can use:

```hbs
{{(get (file-queue named="avatar") 'progress')}}%
```

**Comment by raido** [comment]
Oh, I some how missed that. Thanks!
