### ISSUE TITLE
Acceptable HTML Tags

### ISSUE THREAD

**Issue by shoxter** [tim-evans/ember-file-upload#57]
Why are the elements `div` and `button`, along with many others, disallowed?

Is there a reason for this?

I want to fork the project and add other elements to the list of acceptable tags, but I first need to be sure that there's a reason these are disallowed to begin with.

Thanks!

**Comment by tim-evans** [comment]
The HTML spec disallows block elements in inline-block elements

**Comment by shoxter** [comment]
Thank you!

**Comment by zulaica** [comment]
But wouldn't `fieldset` be a more appropriate containing element rather than `label`? That or even a simple `div` would carry more semantic meaning.

**Comment by zulaica** [comment]
To clarify my comment, my concern is accessibility. An anchor with no `href` attribute doesn't particularly meet accessibility needs. Additionally, it feels like a misuse of `label`. A `button` expresses intent better.

**Comment by ondrejsevcik** [comment]
I'm facing the same issue. `a` tag without href breaks accessibility and on top of that I need to style it like button so it would make much more sense to use actual button as @zulaica pointed out. Can we please reconsider opening this @tim-evans ?

**Comment by ondrejsevcik** [comment]
It should be, it's a global attribute. Maybe the example in a readme should be with an `input` element rather than `a`.

**Comment by tim-evans** [comment]
There's already an input element, it may not be tabbable due to it being hidden. Will investigate.

**Comment by NateDawg90** [comment]
Any update on the file upload being tabbable?
