### ISSUE TITLE
How to abort a file upload

### ISSUE THREAD

**Issue by bartocc** [tim-evans/ember-file-upload#59]
There seems to be code in file and http-request to handle aborting an upload but I could not find the right way to do so.

If this is doable with the current code base, then doc is probably missing.
If it is not doable, then it might be useful adding it.

**Comment by tim-evans** [comment]
`file.upload` returns a cancelable promise, which you can cancel using `cancel`.

so, 

```js
let task = file.upload();
task.cancel();
```

**Comment by bartocc** [comment]
@tim-evans, unfortunately, this snippet does not work for me. `task.cancel` is `undefined`.

I've digged a bit in the code base and I think there might be a bug at https://github.com/tim-evans/ember-file-upload/blob/master/addon/file.js#L96.

This line returns a new promise, not the cancelable one. I have fixed it locally by doing the following

```javascript
  let cancelablePromise = uploadFn(request, options);

  cancelablePromise.then(function (result) {
    set(file, 'state', 'uploaded');
    return result;
  }, function (error) {
    set(file, 'state', 'failed');
    return RSVP.reject(error);
  }).finally(function () {
    // Decrement for Ember.Test
    inflightRequests--;
  });

  return cancelablePromise;
```

What do you reckon ?

**Comment by tim-evans** [comment]
Could you fix this with a PR?

**Comment by tim-evans** [comment]
Thanks for finding this!
