### ISSUE TITLE
Could not find module `rsvp` imported from `ember-file-upload/system/file-reader`

### ISSUE THREAD

**Issue by GendelfLugansk** [tim-evans/ember-file-upload#61]
*ember-file-upload version*: 2.1.1
*Ember version*: 1.13.11

When I try to use example code from readme, I get this error. I suspect it may be due to old ember version. But if I replace `import RSVP from 'rsvp';` with `import {RSVP} from 'ember';`, `ember-file-upload` seems to work (I see a dropzone and can chose a file). Anyone could explain me what the difference between two imports and if it's important for` ember-file-upload`? I understand that first one uses RSVP from rsvp package while second one uses RSVP from ember, which can be different in some way. But does it matter?

**Comment by tim-evans** [comment]
Oh, sorry, this addon only supports 2.0+

**Comment by tim-evans** [comment]
For more context, the `ember-try` config shows what are officially supported :)

**Comment by tim-evans** [comment]
If support farther back is wanted, I'd welcome more additions to the build matrix, as long as it doesn't complicate the code too much.

**Comment by GendelfLugansk** [comment]
Thank you for your answer
