### ISSUE TITLE
No clear distinction between this and ember-plupload

### ISSUE THREAD

**Issue by djsegal** [tim-evans/ember-file-upload#7]
I'm trying to decide between this project and [ember-plupload](https://github.com/tim-evans/ember-plupload), but by briefly comparing the two readme's, I'm still unsure of the real difference. 

I know ember-plupload is basically just a wrapper around `plupload`, I just want to know the advantages of using your `file-upload` logic.

**Comment by tim-evans** [comment]
This is a wip that removes all plupload logic.

It's written for modern browsers. There's still a few kinks to work out :/

**Comment by djsegal** [comment]
@tim-evans sounds good. thanks for the explanation
