### ISSUE TITLE
Implementation of Max File Size Allowed

### ISSUE THREAD

**Issue by Paskalouis** [tim-evans/ember-file-upload#73]
Hello,

Currently, I don't see any handler for max-file-size for file-upload component.
Will it be implemented in future ?
The implementation perhaps will be similar to ember-plupload one.

Thank you

**Comment by tim-evans** [comment]
You can implement that yourself quite easily in your `onfileadd` handler 👍

**Comment by Paskalouis** [comment]
Well yeah, I actually handle this on my onfileadd 👍 

Just suggestion so this is like your ember-plupload. But I guess since can be handled on onfileadd handler this might be not important.

Thank you.

**Comment by tim-evans** [comment]
Yup :)
