### ISSUE TITLE
Release 2.2.1 is about 60mb to download from registry

### ISSUE THREAD

**Issue by janmisek** [tim-evans/ember-file-upload#84]
Is it expected ?

https://registry.yarnpkg.com/ember-file-upload/-/ember-file-upload-2.2.1.tgz

**Comment by janmisek** [comment]
.node_modules.ember-try folder which is 223mb is cause.

**Comment by tim-evans** [comment]
Ooops. This seems to be a bug with deploys. Wondering what was going on locally.

**Comment by tim-evans** [comment]
Fixed in 2.2.3
