### ISSUE TITLE
file-queue helper broken in ember 2.10+

### ISSUE THREAD

**Issue by dwickern** [tim-evans/ember-file-upload#85]
It fails on this line when mutating ember's internal state:
https://github.com/tim-evans/ember-file-upload/blob/cc9557ad3c1219ca511da0fb7989f014962b4401/addon/helpers/file-queue.js#L39

https://www.emberjs.com/blog/2016/11/30/ember-2-10-released.html#toc_other-notable-changes

**Comment by tim-evans** [comment]
Oh dang. Yes. This needs to be a `Ember.copy`

**Comment by tim-evans** [comment]
Fixed in `2.2.2`
