### ISSUE TITLE
file path

### ISSUE THREAD

**Issue by onewiseburdman** [tim-evans/ember-file-upload#93]
Hello all,

I have tried multiple file paths in accordance with your directions and I still end up getting a 404 (
IE.  dist/assets/images/uploads, /dist.../uploads /assets.../uploads, /public/assets/uploads etc...).

Once  I receive the 404 I also get a photo rollback error-which it doesn't look like currently in the example(so I am not sure what to do with that-it needs more details) I attached the errors I am receiving below.  I just don't know how to fix it...  and would really appreciate any help.  

Hoping you can help.

http-request.js:55 POST http://localhost:4200/assets/images/upload 404 (Not Found)
send @ http-request.js:55
(anonymous) @ file.js:321
_upload @ file.js:141
upload @ file.js:309
_callee$ @ upload.js:32
tryCatch @ runtime.js:63
invoke @ runtime.js:337
prototype.(anonymous function) @ runtime.js:96
_resumeGenerator @ -task-instance.js:421
_handleResolvedContinueValue @ -task-instance.js:543
_proceed @ -task-instance.js:507
_scheduleProceed @ -task-instance.js:496
_start @ -task-instance.js:254
_startTaskInstance @ -scheduler.js:105
_flushQueues @ -scheduler.js:80
schedule @ -scheduler.js:63
_performShared @ -task-property.js:413
perform @ -task-property.js:388
uploadImage @ upload.js:61
join @ backburner.js:573
run.join @ ember-metal.js:4464
routeAction @ route-action.js:86
fn @ backburner.js:705
invoke @ backburner.js:274
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:455
_runExpiredTimers @ backburner.js:894
Backburner._boundRunExpiredTimers @ backburner.js:413
setTimeout (async)
Backburner.platform.setTimeout @ backburner.js:399
_installTimerTimeout @ backburner.js:936
_setTimeout @ backburner.js:841
later @ backburner.js:708
run.next @ ember-metal.js:4886
_addFiles @ queue.js:66
change @ component.js:169
run @ backburner.js:537
join @ backburner.js:546
run.join @ ember-metal.js:4464
(anonymous) @ action.js:389
exports.flaggedInstrument @ ember-metal.js:4029
(anonymous) @ action.js:388
rsvp.js:27 Uncaught TypeError: photo.rollback is not a function
    at Class._callee$ (http://localhost:4200/assets/final.js:2414:21)
    at tryCatch (http://localhost:4200/assets/vendor.js:404:40)
    at Generator.invoke [as _invoke] (http://localhost:4200/assets/vendor.js:678:22)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:4200/assets/vendor.js:437:21)
    at Class._resumeGenerator (http://localhost:4200/assets/vendor.js:85635:46)
    at Class._handleResolvedContinueValue (http://localhost:4200/assets/vendor.js:85757:12)
    at Class._proceed (http://localhost:4200/assets/vendor.js:85721:14)
    at invoke (http://localhost:4200/assets/vendor.js:20618:24)
    at Queue.flush (http://localhost:4200/assets/vendor.js:20499:25)
    at DeferredActionQueues.flush (http://localhost:4200/assets/vendor.js:20691:31)

**Comment by onewiseburdman** [comment]
I'm actually glad that it took you guys so long to not even try and answer.  It saved me the money that I was going to spend on one of the creative tim templates.  If you guys can't be even bothered to answer a question, why would I give you any other money at all?

Thankfully closing this ticket without spending a dime.

**Comment by onewiseburdman** [comment]
If a supposed company cannot take the time to acknowledge their consumers-one might want to keep away.

**Comment by tim-evans** [comment]
It is very presumptuous to assume that this project is maintained by a company. I am but a single person maintaining this and have a full time job on top of trying to keep multiple projects up to date.

Please be more empathetic next time you think about posting this on someone's repository- it is hurtful and increases my exhaustion of maintaining such a project. I do appreciate the bug tickets, but if they aren't well structured, I can't dive in and fix the bug quickly. A series of reproducible steps are best to get what you want out of this, with clear points of what you found difficult (whether it's the documentation or the API).
