### ISSUE TITLE
multiple file uploaders on the same page

### ISSUE THREAD

**Issue by xmming** [tim-evans/ember-file-upload#99]
Hi I tried to implement something like this
![muitiple uploaders](https://user-images.githubusercontent.com/8704120/35316209-452ee3a2-0085-11e8-85c5-a78b2d3d1fd5.png)
So I have 5 file-upload and when I clicked each of them, only 1 image can be chosen. And after that image is chosen, a preview of that image will be shown at the position of the input.
However, I found out that these 5 uploaders share the same queue.  Just wondering how I can show the corresponding image of that uploader? Thanks!

**Comment by tim-evans** [comment]
You'll have to name each uploader `{{file-upload name='1'}}`, `{{file-upload name='2'}}`, `{{file-upload name='3'}}`, etc.

**Comment by xmming** [comment]
It works! Thanks a lot!
